kind: Template
apiVersion: v1
metadata:
  name: oslack-alerts
  annotations:
    openshift.io/display-name: "Slack alert application" 
    description: "A simple application to send alerts to slack API"
    iconClass: "icon-play"
    template.openshift.io/provider-display-name: "Apartamento 101"
    template.openshift.io/documentation-url: "https://github.com/cetres/oslack"
    tags: "alert,monitoring,slack"
labels:
  template: oslack-alerts
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: python35
  spec:
    tags:
    - from:
        kind: DockerImage
        name: centos/python-35-centos7:latest
      name: latest

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPLICATION_NAME}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/cetres/oslack"
    strategy:
      type: Source
      sourceStrategy:
          from:
            kind: ImageStreamTag
            name: "python35:latest"
          incremental: true
    output:
      to:
        kind: "ImageStreamTag"
        name: "${APPLICATION_NAME}:latest"

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}
    annotations:
      description: Oslack - Openshift Slack Alerts
  spec:
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APPLICATION_NAME}
          from:
            kind: "ImageStreamTag"
            name: ${APPLICATION_NAME}:latest
    replicas: 1
    selector:
      name: ${APPLICATION_NAME}
    template:
      metadata:
        name: ${APPLICATION_NAME}
        labels:
          name: ${APPLICATION_NAME}
      spec:
        containers:
          - name: ${APPLICATION_NAME}
            env:
              - name: SLACK_API_TOKEN
                value: ${SLACK_API_TOKEN}
              - name: OPENSHIFT_CONSOLE_URL
                value: ${OPENSHIFT_CONSOLE_URL}
            image: ' '
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 20
              timeoutSeconds: 1
            stdin: true
            tty: true

parameters:
- description: The name of the environment
  displayName: Application name
  name: APPLICATION_NAME
  required: true
  value: openshift-slack-alerts
- description: URL where the operator manages OpenShift cluster
  displayName: OpenShift Console URL
  name: OPENSHIFT_CONSOLE_URL
  default: https://openshift.tld:8443
  required: true
- description: The slack token for authorization
  displayName: Slack Token
  name: SLACK_API_TOKEN
  required: true